### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by X-Elie-X** [David-Kasilia/My-Portfolio-Microverse-Project#13]
Uncaught TypeError: closeModal.style is undefined
    closing http://127.0.0.1:5502/script.js:94
    <anonymous> http://127.0.0.1:5502/script.js:97

**Comment by DJ-MrJay** [comment]
Uncaught TypeError: closeModal.style is undefined
closing http://127.0.0.1:5502/script.js:94
http://127.0.0.1:5502/script.js:97
